extends Node

const SAVE_PATH := "user://language.cfg"
const DEFAULT_LANGUAGE := "zh"

signal language_changed

var current_language := DEFAULT_LANGUAGE

const STRINGS := {
	"zh": {
		"game_title": "188号礼物",
		"subtitle": "把家乡的山水装进行囊",
		"guide": "沿着 188 号环线，重演五件小乐事",
		"start": "开启旅程",
		"demo_start": "演示 · 90 秒",
		"demo_hint": "演示模式：这一趟正替评审骑一遍",
		"demo_card_notice": "演示到这里 —— 下面这张明信片，是走完全程的样子",
		"loading": "正在加载中...",
		"language": "🌐 语言 / Language  ⇄",
		"language_current": "中文",
		"road_preview": "五件小乐事 · 即将开启",
		"onboarding_title": "188号礼物",
		"onboarding_subtitle": "沿 188 号环线，重演五件小乐事",
		# 引导页的「这是什么」。顶栏从第一帧就摆着旅币/已过 n/16 驿/心神/下一处
		# 四个数字，但以前这里只讲按键——玩家学完怎么动，仍然不知道自己在干什么。
		# 四个词就是顶栏和碎片栏里出现的全部名词，一次讲完，不用翻帮助。
		"glossary_title": "先认这四样",
		"glossary_lvbi": "旅币",
		"glossary_lvbi_desc": "打卡攒的，驿铺里花",
		"glossary_mood": "心神",
		"glossary_mood_desc": "收一块碎片低一格，雾会变浓",
		"glossary_station": "驿",
		"glossary_station_desc": "路过计数，前六座开灯铺",
		"glossary_fragment": "碎片",
		"glossary_fragment_desc": "五块拼成一份礼物",
		"controls_title": "操作说明",
		"desktop_controls": "键盘操作",
		"mobile_controls": "触屏操作",
		"start_ride": "开始骑行",
		"touch_hint": "摇杆骑行 · 点击按钮打卡 · 右上暂停",
		"desktop_hint": "WASD 骑行 · 空格打卡 · ESC 暂停",
		"key_forward": "加速前进",
		"key_back": "减速 / 倒车",
		"key_left": "左转",
		"key_right": "右转",
		"key_check_in": "靠近驿站时打卡",
		"key_pause": "暂停 / 继续",
		"key_mute": "全局静音",
		"touch_joystick_key": "左下摇杆",
		"touch_joystick_desc": "推杆前进，左右转向",
		"touch_checkin_key": "点击按钮",
		"touch_checkin_desc": "靠近驿站时打卡",
		"touch_buttons_key": "右上按钮",
		"touch_buttons_desc": "暂停 / 静音 / 帮助",
		"pause_title": "游戏暂停",
		"continue": "继续游戏",
		"restart": "重新开始",
		# 结束条件改成"五座碎片驿站各刷满三次"之后，玩家自己喊停的出口就从
		# 「集齐即结算」变成了「只剩重新开始」——低档明信片全部走不到，
		# PostcardVariant 的前四档成了死代码。所以暂停面板给一个自愿收工。
		"finish_run": "结束这一趟 · 收下明信片",
		"finish_run_hint": "还没走满五座驿站，收到的这张按已经走过的算。",
		"help": "操作说明",
		"mute": "全局静音",
		"bgm_mute": "BGM 静音",
		"sfx_mute": "音效静音",
		"on": "开",
		"off": "关",
		"bgm_short": "乐",
		"sfx_short": "效",
		# 画质档位。低/中/高三档切的是**阴影与植被半径**，不切渲染分辨率——
		# Compatibility 下 3D 缩放反而更慢（多一条全屏 blit 通道），而本作零贴图，
		# 想要更多帧只有关阴影、把草皮和行道树收进来这两条路。
		"quality": "画质",
		"quality_low": "低",
		"quality_medium": "中",
		"quality_high": "高",
		# 面板上得说清一件事：切档之后**只有阴影立刻变**，植被半径要重新进这一趟
		# 才看得见（草皮的池和环数在 setup() 那一刻就定死了，当场重建比那点
		# 收益贵得多）。玩家看不到这半句就会以为按钮坏了。
		"quality_hint": "低档关阴影并把草皮行道树收到 70m · 植被范围重新进这一趟生效",
		"help_overlay": "WASD / 方向键  移动\n空格 / Enter     驿站打卡\nESC              暂停菜单\nM               静音开关\n点击碎片图标     查看碎片说明\nBGM/SFX 静音     分别控制背景音乐和音效",
		"help_close": "点击面板外关闭",
		# 原来这里有一个 "progress": "已行 %dkm / 188km"。世界只有 1228.8m 一圈，
		# 这个换算出来是 7200km/h，玩家一眼就能算穿，所以顶栏早就改挂驿数
		# （stations_seen）了。但 key 没删，于是 verify_economy 的 km 扫描
		# 不得不为它单开一条豁免 —— 一条看起来齐全的回归，恰好漏掉了全表里
		# 唯一真带着里程的一句。删掉 key，豁免也跟着删，扫描不再有后门。
		"stations_seen": "已过 %d/%d 驿",
		"fragments": "碎片 %d/5",
		"hud_next_target": "下一处 %s %s · %dm",
		"hud_revisit_target": "再访 %s %s · 还差 %s 次",
		"hud_all_done": "五座都走满了 · 正在收尾",
		"visits_left_n": "%d",
		"dusk_began": "天要暗了。灯亮起来，路还是那条路。",
		"touch_checkin_prompt": "点击按钮 · 在此完成乐事",
		"desktop_checkin_prompt": "空格 · 在此完成乐事",
		"desktop_revisit_prompt": "空格 · 再办一次 · 还差 %d",
		"touch_revisit_button": "再访",
		"blocked_cooldown": "刚刚才结束 · 稍等一下",
		"blocked_recheck": "先骑开一点再来",
		"blocked_busy": "这里现在进不去",
		"touch_checkin_button": "完成乐事",
		"fragment_obtained": "获得碎片：",
		"revisit_note": "这件已经在你手里了。坐一会儿，看看远处的山。",
		# collecting_message 原来写的是"礼物正在合成…"，而它同时也是这一趟的
		# 结束提示——于是第一次集齐时玩家被锁死 2.5 秒弹去结算页，
		# 顶栏一路写的「再访 · 还差 N 次」一句也兑现不了。
		# 现在集齐只放动画不放人：礼物成形了，乐事还能再收。
		"collecting_message": "五件乐事已集齐，礼物成形了。",
		"revisit_available": "顶栏的圆点还是空的——每座驿站都还能再去两次。",
		"synthesis_take_postcard": "收下明信片 · 结束这一趟",
		"synthesis_keep_riding": "再骑一圈 · 刷到完满",
		"synthesis_choice_hint": "一趟已经跑通了：五件乐事、五个字、一张明信片。想刷「完满」，每座驿站都还能再去两次。",
		"synthesis_done_message": "五座驿站都走满了。礼物成形…",
		# 交叉点那块碑的题字。碑面刻的是路自己的形状（RoadData.points 生成），
		# 这一句只是落款——"这里是交叉点"那句话只是在复述坐标。
		"crossing_mark_line": "路自此复",
		"hint_close": "点击任意处关闭",
		"fragment_0": "云",
		"fragment_1": "茶",
		"fragment_2": "琴",
		"fragment_3": "竹",
		"fragment_4": "禽",
		"fragment_tip_0": "雨后登楼，看山色空蒙",
		"fragment_tip_1": "客至汲泉烹茶，朋友来了",
		"fragment_tip_2": "抚琴听者知音，弦上千年意",
		"fragment_tip_3": "微雨竹窗夜话，竹窗一开",
		"fragment_tip_4": "飞来佳禽自语，天地也回礼",
		"export": "导出明信片",
		"share": "复制分享文案",
		"restart_end": "重新开始",
		"exported": "明信片已下载",
		"saved_to": "已保存至 ",
		"export_failed": "导出失败，请重试",
		"copied": "已复制 ✓",
		"share_text": "我沿着一条 8 字形的环形路线，经过 16 座驿站，在其中 5 座完成了五件小乐事，合成了一份礼物 No.188。\n云影、茶烟、琴音、竹雨、禽语——五件小乐事拼成一幅骑行长卷。\nA Gift for No.188 · 3D Ride #Tripothon",
		"dialogue_next": "下一句 ▶",
		"dialogue_skip": "跳过 >>",
		"dialogue_start": "开始游戏 ✚",
		"postcard_signature": "No.188 · 五件小乐事 · 记五",
		"postcard_variant_hint": "同一处驿站再访两次，第五格才落成真禽。",
		# ---- 明信片正面顶部那一块：这一趟的路线图 ----
		# 正面原先顶部是一段云天、五块碎片排成五格色卡，谁看都是同一张。
		# 换成「你实际骑过的那条路」之后，正面才真的属于这一趟。
		"postcard_map_title": "这一趟的路线",
		"postcard_map_legend": "实心 = 到过　空心 = 未至",
		# 抬头右半那列。**原来那一带是空白的纸**——五个到访次数挤在
		# 「已过 n/16 驿」底下那一行，剩下三分之一什么也没有。
		"postcard_joys_title": "五件乐事",
		"postcard_visit_n": "%d 次",
		# ---- 重新开始前的「这一趟」回执（EndCard._show_run_recap）----
		# 动机不是分数，是**这一趟真实没碰过的东西**：没读到的风景话、没赢过的
		# 小乐事、没去过的驿站、没走过的另一边。全部由存档里的既有字段推出来，
		# 不新增任何进度写入；玩家没做的事不编，编了就是骗他再骑一趟。
		"recap_title": "这一趟还剩下这些",
		"recap_frag_missing": "还差这几块没拿到：%s",
		"recap_frag_one": "还差这一块没拿到：%s",
		"recap_seen": "路过 %d/%d 座驿站",
		"recap_unread": "没读到它们的话：%s",
		"recap_mini": "五件小乐事赢了 %d 件",
		"recap_mini_lost": "没赢过：%s",
		"recap_ending": "你选了【%s】，另一边还空着",
		"recap_tier": "明信片带出去 %d 件散件",
		"recap_lvbi": "还剩 %d 旅币没花出去",
		"recap_again": "再骑一趟",
		"recap_stay": "留下这张卡",
		"disclaimer": "本作为虚构叙事 Demo。路线形状、驿站名称与场景布局均为艺术化重排，\n取材于公有领域的东坡诗文，与任何现实旅游公路、官方驿站品牌或景区运营无关。",
		"write_back": "写背面",
		"back_editor_title": "在背面写下你的祝福",
		"back_placeholder": "写下你想说的话…（最多200字）",
		"back_confirm": "确认 / Confirm",
		"back_skip": "跳过，直接导出",
		"back_preview_caption": "写完是这样",
		"back_to_front": "< 返回编辑",
		"postcard_back_title": "第188号路线 · 礼物",
		"postcard_back_from": "—— 来自第188号路线",
		"postcard_seal": "完",
		"mg_cloud_title": "沿着云朵轨迹绘制",
		"mg_cloud_hint": "方向键 / WASD 挪光标 · 按住空格落笔 · ESC 取消",
		"mg_key_hint": "按 1 / 2 / 3 / 4 选择 · ESC 取消",
		"mg_tea_title": "按住注水，3秒后完成",
		"mg_tea_left": "还差 %.1f 秒",
		"mg_tea_hint_hold": "按住 SPACE 或 点击屏幕 注水",
		"mg_tea_hint_release": "松手就退回零 · 按住别放",
		"mg_tea_hint_esc": "· ESC 放弃",
		"mg_zither_title": "古琴 · 记住这一段琴音，再照着弹回来",
		"mg_zither_watch": "观察… 第 %d/%d 个",
		"mg_zither_turn": "你的回合 (%d/%d) — 剩余 %.0f 秒",
		"mg_bamboo_title": "竹子一冒头就按空格！",
		"mg_bamboo_intro": "竹子一冒头就能砍，现在就按空格 · ESC 放弃",
		"mg_bamboo_done": "五根全倒，竹雨庭清空！",
		"mg_bird_title": "记住这只鸟！",
		"mg_bird_sub": "稍后会问你是哪一只",
		"mg_bird_question": "刚才的鸟是哪一只？",
		"mg_bird_0": "麻雀",
		"mg_bird_1": "燕子",
		"mg_bird_2": "白鹭",
		"mg_bird_3": "乌鸦",
		"mg_progress": "进度: %d/%d",
		"mg_complete": "完成度: %d%%（到 %d%% 算过）",
		"mg_cancel": "取消",
		"mg_failed": "这次没有完成",
		"mg_failed_hint": "别灰心 —— 骑开一点再折回来，这个驿站还能再挑战一次",
		"lvbi_label": "旅币 %d",
		"mood_label": "心神 %d/%d",
		"collecting_lvbi": "+%d 旅币",
		"shop_balance": "旅币 %d",
		"shop_buy": "买 · %d",
		"shop_bought": "已购",
		"shop_mood_full": "心神已满",
		"shop_maxed": "买满了",
		"shop_need_lvbi": "旅币不够",
		"shop_need_frags": "需要 %d 块碎片",
		"shop_lower_tier": "已有更好的一档",
		"shop_locked": "先过 %d 座驿才亮",
		"shop_close": "离开小铺",
		"touch_shop_prompt": "点击按钮 · 进入小铺",
		"desktop_shop_prompt": "空格 · 进入小铺",
		"shop_enter_button": "进入小铺",
		"shop_nfs_title": "无价",
		# 原来写"路上自取"——游戏里没有任何地方能自取，玩家看到的是一堵
		# 买不了也拿不到的死墙。改成说清楚这五个字到底去哪：明信片正面。
		"shop_nfs_hint": "买不到。走完全程，五件会落在明信片正面。",
		"tier_plain": "素笺",
		"tier_fine": "上笺",
		"tier_rare": "珍藏笺",
		"ending_title": "终点 · 落笔",
		"ending_hint": "两边各留一样东西在这张卡上：背面写不写，封口的蜡封不封。选一边，另一边就没了。",
		"ending_keep": "留门",
		"ending_break": "放手",
		"back_keep": "「十八驿」那家旅店还在我这儿。你迷路的时候，敲一下门。",
		"back_break": "这条路走完了。下一程，你自己认。",
		"back_break_blank": "背面留白，封口的蜡已经掰开。\n这句话不再替你写——拿不拿，你自己定。",
		"prologue_speaker": "路俊航",
		"player_speaker": "路俊航",
		"villain_speaker": "郑铎",
		# 郑铎三场之前各浮一句"有人找你"。三句都短、都不剧透：这一屏要解决的
		# 不是"交代剧情"，是让玩家知道刚才那一下是有人找他，不是游戏卡了。
		"villain_cue_1": "手机响了。",
		"villain_cue_2": "对讲机里有人在喊你的名字。",
		"villain_cue_3": "最后一通。",
		"prologue_1": "律师函到了。\n十八驿温泉旅驿闲置六年，三十日内不开业，依法征收。\n\n先回去看看吧。",
		"prologue_2": "妈，你走的时候，山还在。\n你现在在哪儿？",
		"prologue_3": "守驿人记路，不记己。\n你替所有人记住回家的路。\n代价是——没有人记得你。",
		"villain_1_1": "路先生？云岭文旅，郑铎。",
		"villain_1_2": "公事公办——这块地闲置六年了。三十天内不开业，依法收回。",
		"villain_1_3": "顺带一提，山里有几处旧路基属于规划红线。别乱走。",
		"villain_2_1": "南边岔口往下一段有一处老路基，地图上查不到。我们从上面挖出一块刻字的石头。",
		"villain_2_2": "你母亲当年也去看过那块石头。她之后，就没再回来。",
		"villain_2_3": "别学她。",
		"villain_3_1": "五天内不签字，这块地依法收回。",
		"villain_3_2": "说清楚吧——我们真正想要的，是温泉底下那个东西。",
		"villain_3_player": "那迷路的人呢？",
		"villain_3_3": "……你问我这个？我不信那套。打开它，这条路就是我们的。",
		# ---- 四块路碑（RoadSteles）。碑面上刻的只有「188」，
		# 中英一样，所以只有浮出来的那四句要双语。----
		"stele_1_line": "守驿人记路，不记己。",
		"stele_2_line": "你替所有人记住回家的路。",
		"stele_3_line": "编号 188。这条路认得每一个走过的人。",
		"stele_4_line": "字被人凿平了。只剩半个 188。",
	},
	"en": {
		"game_title": "Gift No.188",
		"subtitle": "Pack the landscape into your bag.",
		"guide": "Along the No.188 loop, replay five small joys.",
		"start": "Start Journey",
		"demo_start": "Demo · 90s",
		"demo_hint": "Demo mode: this run is being ridden for you",
		"demo_card_notice": "That's the demo — the postcard below is what a finished run looks like",
		"loading": "Loading...",
		"language": "语言 / Language",
		"language_current": "English",
		"road_preview": "Five small joys · coming soon",
		"onboarding_title": "Gift No.188",
		"onboarding_subtitle": "Along the No.188 loop, relive five small joys",
		"glossary_title": "Four things to know",
		"glossary_lvbi": "Coins",
		"glossary_lvbi_desc": "Earned by checking in; spent in shops",
		"glossary_mood": "Heart",
		"glossary_mood_desc": "One per fragment; lower means thicker fog",
		"glossary_station": "Stations",
		"glossary_station_desc": "Counted as you pass; the first six open a shop",
		"glossary_fragment": "Fragments",
		"glossary_fragment_desc": "Five of them make one gift",
		"controls_title": "Controls",
		"desktop_controls": "Keyboard Controls",
		"mobile_controls": "Touch Controls",
		"start_ride": "Start Riding",
		"touch_hint": "Joystick to ride · tap button to check in · pause at top right",
		"desktop_hint": "WASD to ride · Space to check in · ESC to pause",
		"key_forward": "Accelerate",
		"key_back": "Slow down / reverse",
		"key_left": "Turn left",
		"key_right": "Turn right",
		"key_check_in": "Check in near a station",
		"key_pause": "Pause / resume",
		"key_mute": "Mute all",
		"touch_joystick_key": "Left joystick",
		"touch_joystick_desc": "Push to ride and steer",
		"touch_checkin_key": "Tap button",
		"touch_checkin_desc": "Check in near a station",
		"touch_buttons_key": "Top-right buttons",
		"touch_buttons_desc": "Pause / mute / help",
		"pause_title": "Paused",
		"continue": "Continue",
		"restart": "Restart",
		"finish_run": "End this ride · Keep the postcard",
		"finish_run_hint": "Not every post walked yet — this one is rated on what you did ride.",
		"help": "Controls",
		"mute": "Mute all",
		"bgm_mute": "BGM mute",
		"sfx_mute": "SFX mute",
		"on": "On",
		"off": "Off",
		"bgm_short": "Music",
		"sfx_short": "SFX",
		"quality": "Quality",
		"quality_low": "Low",
		"quality_medium": "Medium",
		"quality_high": "High",
		"quality_hint": "Low turns off sun shadows and pulls grass and trees in to 70m - vegetation range applies on your next ride",
		"help_overlay": "WASD / Arrows   Move\nSpace / Enter   Station check-in\nESC             Pause menu\nM               Mute all\nTap shard icon  View shard story\nBGM/SFX mute    Control music and sounds",
		"help_close": "Click outside the panel to close",
		"stations_seen": "Posts passed %d/%d",
		"fragments": "Shards %d/5",
		"hud_next_target": "Next %s %s · %dm",
		"hud_revisit_target": "Revisit %s %s · %s to go",
		"hud_all_done": "All five walked · wrapping up",
		"visits_left_n": "%d",
		"dusk_began": "Evening is coming on. The lamps come up; the road is the same road.",
		"touch_checkin_prompt": "Tap the button · complete the joy here",
		"desktop_checkin_prompt": "Space · complete the joy here",
		"desktop_revisit_prompt": "Space · once more · %d to go",
		"touch_revisit_button": "Visit",
		"blocked_cooldown": "Just finished · give it a moment",
		"blocked_recheck": "Ride a little further first",
		"blocked_busy": "Not right now",
		"touch_checkin_button": "Complete Joy",
		"fragment_obtained": "Shard obtained: ",
		"revisit_note": "This one's already yours. Sit a while and watch the hills.",
		"collecting_message": "All five joys collected. The gift is formed.",
		"revisit_available": "The pips in the top bar are still open — two more visits to every post.",
		"synthesis_take_postcard": "Keep the postcard · End this ride",
		"synthesis_keep_riding": "One more lap · For the full rating",
		"synthesis_choice_hint": "One loop is a whole run: five joys, five characters, one postcard. For the full rating, two more visits to every post.",
		"synthesis_done_message": "Every post walked three times over. The gift is forming...",
		"crossing_mark_line": "Here the road doubles back",
		"hint_close": "Click anywhere to close",
		"fragment_0": "Cloud",
		"fragment_1": "Tea",
		"fragment_2": "Music",
		"fragment_3": "Bamboo",
		"fragment_4": "Bird",
		"fragment_tip_0": "Watch the mountains soften after rain",
		"fragment_tip_1": "Brew tea when a friend arrives",
		"fragment_tip_2": "A zither melody finds its listener",
		"fragment_tip_3": "Night rain talks through the bamboo",
		"fragment_tip_4": "A bird answers the lake in its own language",
		"export": "Export Postcard",
		"share": "Copy Share Text",
		"restart_end": "Restart",
		"exported": "Postcard downloaded",
		"saved_to": "Saved to ",
		"export_failed": "Export failed. Please try again.",
		"copied": "Copied ✓",
		"share_text": "I rode a figure-eight loop past 16 stations, completed five small joys at five of them, and made Gift No.188.\nCloudshadow, tea steam, zither wind, bamboo rain, and birdsong became one riding postcard.\nA Gift for No.188 · 3D Ride #Tripothon",
		"dialogue_next": "Next ▶",
		"dialogue_skip": "Skip >>",
		"dialogue_start": "Start ✚",
		"postcard_signature": "No.188 · Five Small Joys · Ride Complete",
		"postcard_variant_hint": "Visit one station twice more and the last panel fills in.",
		"postcard_map_title": "The route you rode",
		"postcard_map_legend": "Filled = passed　Hollow = not yet",
		"postcard_joys_title": "The five joys",
		"postcard_visit_n": "%d visits",
		"recap_title": "What this run left out",
		"recap_frag_missing": "Still missing: %s",
		"recap_frag_one": "Still missing: %s",
		"recap_seen": "Passed %d/%d stations",
		"recap_unread": "You never read what they had to say: %s",
		"recap_mini": "You won %d of the five small joys",
		"recap_mini_lost": "Never won: %s",
		"recap_ending": "You chose %s — the other one is still empty.",
		"recap_tier": "%d extra pieces went out on the postcard",
		"recap_lvbi": "%d travel coins still unspent",
		"recap_again": "Ride again",
		"recap_stay": "Keep this card",
		"disclaimer": "This is a fictional narrative demo. The route shape, station names,\nand scene layout are artistic rearrangements inspired by public-domain poetry,\nand are not affiliated with any real tourism road, official station brand, or scenic area.",
		"write_back": "Write on Back",
		"back_editor_title": "Write your wish on the back",
		"back_placeholder": "Write something… (up to 200 characters)",
		"back_confirm": "Confirm",
		"back_skip": "Skip and export",
		"back_preview_caption": "How it will look",
		"back_to_front": "< Back to edit",
		"postcard_back_title": "Route No.188 · The Gift",
		"postcard_back_from": "— From Route No.188",
		"postcard_seal": "ALL",
		"mg_cloud_title": "Trace along the cloud's path",
		"mg_cloud_hint": "Arrows / WASD to move · hold SPACE to draw · ESC to cancel",
		"mg_key_hint": "Press 1 / 2 / 3 / 4 · ESC to cancel",
		"mg_tea_title": "Hold to pour — finish in 3 seconds",
		"mg_tea_left": "%.1fs to go",
		"mg_tea_hint_hold": "Hold SPACE or click to pour",
		"mg_tea_hint_release": "Let go and it drains back to zero",
		"mg_tea_hint_esc": " · ESC to give up",
		"mg_zither_title": "Guqin — remember this phrase, then play it back",
		"mg_zither_watch": "Watch… note %d of %d",
		"mg_zither_turn": "Your turn (%d/%d) — %.0fs left",
		"mg_bamboo_title": "Press SPACE the moment a bamboo appears!",
		"mg_bamboo_intro": "Cut it the moment it appears — press SPACE now · ESC to give up",
		"mg_bamboo_done": "All five down — the grove is clear!",
		"mg_bird_title": "Remember this bird!",
		"mg_bird_sub": "You'll be asked which one it was",
		"mg_bird_question": "Which bird was it?",
		"mg_bird_0": "Sparrow",
		"mg_bird_1": "Swallow",
		"mg_bird_2": "Egret",
		"mg_bird_3": "Crow",
		"mg_progress": "Progress: %d/%d",
		"mg_complete": "Done: %d%% (%d%% to pass)",
		"mg_cancel": "Cancel",
		"mg_failed": "Not completed this time",
		"mg_failed_hint": "No worries — ride a little ways and come back. This station can be challenged again.",
		"lvbi_label": "Lvbi %d",
		"mood_label": "Composure %d/%d",
		"collecting_lvbi": "+%d lvbi",
		"shop_balance": "Lvbi %d",
		"shop_buy": "Buy · %d",
		"shop_bought": "Owned",
		"shop_mood_full": "Composure already full",
		"shop_maxed": "Fully owned",
		"shop_need_lvbi": "Not enough lvbi",
		"shop_need_frags": "Needs %d shards",
		"shop_lower_tier": "Already have a finer sheet",
		"shop_locked": "Lights up after %d posts",
		"shop_close": "Leave the shop",
		"touch_shop_prompt": "Tap button · Enter shop",
		"desktop_shop_prompt": "Space · Enter shop",
		"shop_enter_button": "Enter Shop",
		"shop_nfs_title": "Priceless",
		"shop_nfs_hint": "Cannot be bought. Ride to the end — all five land on the postcard's front.",
		"tier_plain": "Plain Sheet",
		"tier_fine": "Fine Sheet",
		"tier_rare": "Rare Sheet",
		"ending_title": "The End · A Line to Write",
		"ending_hint": "Each leaves one thing on this card: whether the back gets written, whether the wax stays sealed. Pick one and the other is gone.",
		"ending_keep": "Leave the Door",
		"ending_break": "Let Go",
		"back_keep": "The Eighteenth Post inn is still here with me. If you are lost, knock.",
		"back_break": "This road is walked out. The next stretch, you find yourself.",
		"back_break_blank": "The back stays blank and the wax is already broken open.\nThe line is no longer written for you — take it or leave it.",
		"prologue_speaker": "Lu Junhang",
		"player_speaker": "Lu Junhang",
		"villain_speaker": "Zheng Duo",
		"villain_cue_1": "Your phone buzzes.",
		"villain_cue_2": "Someone says your name over the radio.",
		"villain_cue_3": "The last call.",
		"prologue_1": "The lawyer's letter arrived.\nThe Eighteenth Post has lain idle for six years. Open it within thirty days, or the land is taken by law.\n\nI'll go back and take a look.",
		"prologue_2": "When you left, the mountains were still here, Mother.\nWhere are you now?",
		"prologue_3": "The keeper remembers the road, not himself.\nYou remember the way home for everyone.\nThe price is that no one remembers you.",
		"villain_1_1": "Mr. Lu? Zheng Duo, Yunling Cultural Tourism.",
		"villain_1_2": "Business, plain and simple — the land has been idle six years. Open it within thirty days, or it is taken back by law.",
		"villain_1_3": "Also, some of the old road beds in the mountains fall inside a planning red line. Don't wander off.",
		"villain_2_1": "Past the fork to the south there's an old road bed you can't find on any map. We dug an inscribed stone out of it.",
		"villain_2_2": "Your mother went to see that same stone, back in her day. After that, she never came back.",
		"villain_2_3": "Don't follow her.",
		"villain_3_1": "If I don't get a signature in five days, the land is taken back by law.",
		"villain_3_2": "Let me be clear — what we actually want is the thing under the hot spring.",
		"villain_3_player": "And the people who get lost?",
		"villain_3_3": "...You ask me that? I don't buy any of it. Open it, and this road is ours.",
		# ---- Four road steles (RoadSteles). The carving itself is only "188",
		# identical in both languages; only the line that floats up needs two. ----
		"stele_1_line": "The keeper remembers the road, not himself.",
		"stele_2_line": "You keep the way home for everyone.",
		"stele_3_line": "Marked No.188. This road knows everyone who has walked it.",
		"stele_4_line": "The letters have been chiselled away. Half a 188 is all that's left.",
	}
}


func _ready() -> void:
	_load_language()


func t(key: String, args: Array = []) -> String:
	var value: String = STRINGS.get(current_language, STRINGS[DEFAULT_LANGUAGE]).get(key, key)
	if args.is_empty():
		return value
	return value % args


func set_language(language: String) -> void:
	if not STRINGS.has(language):
		return
	current_language = language
	TranslationServer.set_locale("en" if language == "en" else "zh_CN")
	_save_language()
	language_changed.emit()


func get_current_language() -> String:
	return current_language


func is_english() -> bool:
	return current_language == "en"


func _load_language() -> void:
	var cfg = ConfigFile.new()
	if cfg.load(SAVE_PATH) != OK:
		set_language(DEFAULT_LANGUAGE)
		return
	set_language(cfg.get_value("ui", "language", DEFAULT_LANGUAGE))


func _save_language() -> void:
	var cfg = ConfigFile.new()
	cfg.set_value("ui", "language", current_language)
	if cfg.save(SAVE_PATH) != OK:
		push_warning("Language save failed: %s" % SAVE_PATH)
